export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_SHOPPING_CART = 'GET_SHOPPING_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const EMPTY_CART = 'EMPTY_CART';
export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY';
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY';
export const PRODUCTS_ERROR = 'PRODUCTS_ERROR';
export const GET_USER = 'GET_USER';
export const USER_ERROR = 'USER_ERROR';


